// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// evaluate_imputation
List evaluate_imputation(List true_data, List imputed_data, std::string method);
RcppExport SEXP _imputetoolkit_evaluate_imputation(SEXP true_dataSEXP, SEXP imputed_dataSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type true_data(true_dataSEXP);
    Rcpp::traits::input_parameter< List >::type imputed_data(imputed_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate_imputation(true_data, imputed_data, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imputetoolkit_evaluate_imputation", (DL_FUNC) &_imputetoolkit_evaluate_imputation, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_imputetoolkit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
