# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluate_imputation_split <- function(true_data, imputed_data, numeric_cols, categorical_cols, method) {
    .Call(`_imputetoolkit_evaluate_imputation_split`, true_data, imputed_data, numeric_cols, categorical_cols, method)
}

evaluate_imputation <- function(true_data, imputed_data, method) {
    .Call(`_imputetoolkit_evaluate_imputation`, true_data, imputed_data, method)
}

