# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluate_imputation <- function(true_vals, imputed_vals, method) {
    .Call(`_imputetoolkit_evaluate_imputation`, true_vals, imputed_vals, method)
}

